_BASE_: ../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2ConvNext"
  CONVNEXT:
    EMBED_DIM: [96, 192, 384, 768]
    DEPTHS: [3, 3, 27, 3]
  WEIGHTS: "convnext_small_1k_224_ema.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
