_BASE_: ../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2ConvNextV2"
  CONVNEXTV2:
    EMBED_DIM: [40, 80, 160, 320]
    DEPTHS: [2, 2, 6, 2]
  WEIGHTS: "convnextv2_atto_1k_224_ema.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
