_BASE_: ../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2STDCnet"
  STDC:
    LAYERS: [4,5,3]
  WEIGHTS: "STDCNet1446_76.47.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
